version: "3"

tasks:
  build:
    cmds: 
      - crystal build ./src/main.cr -o build/LinkShort-cli{{exeExt}}
  build-release:
    cmds:
      - crystal build ./src/main.cr -o build/LinkShort-cli{{exeExt}} --release